# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19z5PW6iSBjAQDJYgJzvRIEwyo1QmqooI
"""

# =========================
# PREDICTION BUTTON
# =========================

center_col = st.columns([1, 2, 1])

with center_col[1]:

    if st.button("🔍 Predict Subscription", use_container_width=True):

        prediction = model.predict(input_data)[0]
        probability = model.predict_proba(input_data)[0][1]

        st.divider()

        st.subheader("📌 Prediction Result")

        if prediction == 1:

            st.success(
                f"""
                ✅ Client is LIKELY to subscribe

                Probability of Subscription: {probability:.2%}
                """
            )

        else:

            st.error(
                f"""
                ❌ Client is UNLIKELY to subscribe

                Probability of Subscription: {probability:.2%}
                """
            )

        st.divider()

        st.subheader("📋 Input Summary")

        summary_df = input_data.T
        summary_df.columns = ["Value"]

        st.table(summary_df)