# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19z5PW6iSBjAQDJYgJzvRIEwyo1QmqooI
"""

import streamlit as st
import pandas as pd
import joblib

# Load model
model = joblib.load('rsmb_model.pkl')

# Page Title
st.title("RS-MB Bank Marketing Prediction")

st.write(
    "Predict whether a customer will subscribe "
    "to a term deposit."
)

# ======================
# USER INPUTS
# ======================

age = st.number_input("Age", 18, 100, 30)

job = st.selectbox(
    "Job",
    [
        'admin.',
        'blue-collar',
        'entrepreneur',
        'housemaid',
        'management',
        'retired',
        'self-employed',
        'services',
        'student',
        'technician',
        'unemployed'
    ]
)

marital = st.selectbox(
    "Marital Status",
    ['married', 'single', 'divorced']
)

education = st.selectbox(
    "Education",
    [
        'basic.4y',
        'basic.6y',
        'basic.9y',
        'high.school',
        'professional.course',
        'university.degree'
    ]
)

default = st.selectbox(
    "Credit Default",
    ['no', 'yes']
)

housing = st.selectbox(
    "Housing Loan",
    ['no', 'yes']
)

loan = st.selectbox(
    "Personal Loan",
    ['no', 'yes']
)

contact = st.selectbox(
    "Contact Type",
    ['cellular', 'telephone']
)

campaign = st.number_input(
    "Campaign Contacts",
    1,
    50,
    1
)

previous = st.number_input(
    "Previous Contacts",
    0,
    20,
    0
)

emp_var_rate = st.number_input(
    "Employment Variation Rate",
    -5.0,
    5.0,
    1.1
)

cons_price_idx = st.number_input(
    "Consumer Price Index",
    90.0,
    100.0,
    93.0
)

cons_conf_idx = st.number_input(
    "Consumer Confidence Index",
    -60.0,
    0.0,
    -40.0
)

euribor3m = st.number_input(
    "Euribor 3M Rate",
    0.0,
    10.0,
    4.0
)

nr_employed = st.number_input(
    "Number of Employees",
    4000.0,
    6000.0,
    5000.0
)

# ======================
# PREDICTION
# ======================

if st.button("Predict"):

    input_data = pd.DataFrame({
        'age': [age],
        'job': [job],
        'marital': [marital],
        'education': [education],
        'default': [default],
        'housing': [housing],
        'loan': [loan],
        'contact': [contact],
        'campaign': [campaign],
        'previous': [previous],
        'emp.var.rate': [emp_var_rate],
        'cons.price.idx': [cons_price_idx],
        'cons.conf.idx': [cons_conf_idx],
        'euribor3m': [euribor3m],
        'nr.employed': [nr_employed]
    })

    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]

    if prediction == 1:
        st.success(
            f"Customer likely to subscribe "
            f"({probability:.2%})"
        )
    else:
        st.error(
            f"Customer unlikely to subscribe "
            f"({probability:.2%})"
        )