# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19z5PW6iSBjAQDJYgJzvRIEwyo1QmqooI
"""

import streamlit as st
import pandas as pd
import joblib

# Load trained RS-MB model
model = joblib.load('rsmb_model.pkl')

# Page configuration
st.set_page_config(
    page_title="Customer Subscription to Bank Term Deposits Predictor using RS-MB",
    page_icon="📈",
    layout="centered"
)

# Title
st.title("📈 RS-MB Bank Marketing Prediction App")

st.markdown("""
This application predicts whether a client is likely to subscribe to a term deposit
using the RS-MB Hybrid Ensemble Model.
""")

st.divider()

# =========================
# USER INPUTS
# =========================

default = st.selectbox(
    "Has Credit Default?",
    ["yes", "no"]
)

housing = st.selectbox(
    "Has Housing Loan?",
    ["yes", "no"]
)

loan = st.selectbox(
    "Has Personal Loan?",
    ["yes", "no"]
)

previous = st.number_input(
    "Number of Previous Contacts",
    min_value=0,
    value=0,
    step=1
)

poutcome = st.selectbox(
    "Previous Campaign Outcome",
    ["Failure", "Nonexistent", "Success"]
)

emp_var_rate = st.number_input(
    "Employment Variation Rate",
    value=1.1
)

cons_price_idx = st.number_input(
    "Consumer Price Index",
    value=93.994
)

cons_conf_idx = st.number_input(
    "Consumer Confidence Index",
    value=-36.4
)

euribor3m = st.number_input(
    "Euribor 3 Month Rate",
    value=4.857
)

age_group = st.selectbox(
    "Age Group",
    ["Young", "Middle-aged", "Senior"]
)

lead_type = st.selectbox(
    "Lead Type",
    ["New", "Existing"]
)

# =========================
# CREATE INPUT DATAFRAME
# =========================

input_data = pd.DataFrame({
    'default': [default],
    'housing': [housing],
    'loan': [loan],
    'previous': [previous],
    'poutcome': [poutcome],
    'emp.var.rate': [emp_var_rate],
    'cons.price.idx': [cons_price_idx],
    'cons.conf.idx': [cons_conf_idx],
    'euribor3m': [euribor3m],
    'age_group': [age_group],
    'lead_type': [lead_type]
})

# =========================
# PREDICTION BUTTON
# =========================

if st.button("Predict Subscription"):

    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]

    st.subheader("Prediction Result")

    if prediction == 1:
        st.success(
            f"✅ Client is LIKELY to subscribe "
            f"({probability:.2%} probability)"
        )
    else:
        st.error(
            f"❌ Client is UNLIKELY to subscribe "
            f"({probability:.2%} probability)"
        )

    st.divider()

    st.subheader("Input Summary")
    st.write(input_data.T)